# Generated by Django 5.0.6 on 2024-07-31 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='job_studies',
        ),
    ]
