# Generated by Django 5.0.6 on 2024-08-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_alumni_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='current_position',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
