# Generated by Django 5.0.6 on 2024-08-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_alter_alumni_current_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='faculty_pictures/'),
        ),
    ]
