# Generated by Django 5.0.6 on 2025-02-09 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_current_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_student',
            name='linkedin',
        ),
    ]
