# Generated by Django 5.0.6 on 2025-02-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_remove_current_student_linkedin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Current_Student',
        ),
    ]
