# Generated by Django 5.0.6 on 2024-07-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='phone',
        ),
        migrations.AddField(
            model_name='faculty',
            name='area_of_interest',
            field=models.TextField(blank=True, null=True),
        ),
    ]
