# Generated by Django 5.0.6 on 2024-07-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_remove_faculty_phone_faculty_area_of_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='publications',
            field=models.URLField(blank=True, null=True),
        ),
    ]
