# Generated by Django 5.0.6 on 2025-02-09 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_routine'),
        ('documents', '0004_alter_document_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('already_studied', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('about', models.TextField()),
                ('video', models.URLField(max_length=1000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_documents', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.my_document')),
            ],
        ),
    ]
