# Generated by Django 5.0.6 on 2025-02-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticemodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
