# Generated by Django 5.0.6 on 2025-02-13 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_note', '0002_alter_noticemodel_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoticeModel',
        ),
    ]
